author: yanm1ng # 作者
description: yanm1ng's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# gitment
gitment_owner: shawflying
gitment_repo: https://github.com/shawflying/yxxit-blog/issues
gitment_oauth_id: 66cdd646a4b3f9468cee
gitment_oauth_secret: 01ada0c8f17bec5d1a9766575b60996cbc05a2a7

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: /view/img/webp/about.webp
  avatar: /view/img/webp/header.webp
  description: The end is always near.